import { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, AlignmentType, WidthType, BorderStyle } from "docx";
import jsPDF from "jspdf";
import JSZip from "jszip";
import { GeneratedAssessment } from "../types";

// Standard browser anchor download helper for Blog/Chunks to prevent extra dependency issues
const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Generates DOCX for Kisi-Kisi
 */
export const generateKisiKisiDocx = async (assessment: GeneratedAssessment) => {
  const meta = assessment.metadata;

  const titlePara = new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({ text: "KISI-KISI SELEKSI SOAL UJIAN", bold: true, size: 28, font: "Arial" }),
      new TextRun({ text: `\n${assessment.title.toUpperCase()}`, bold: true, size: 24, font: "Arial" }),
    ],
  });

  const spacePara = new Paragraph({ children: [new TextRun({ text: "" })] });

  // Class Meta Table
  const metaRows = [
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph("Mata Pelajaran")], width: { size: 30, type: WidthType.PERCENTAGE } }),
        new TableCell({ children: [new Paragraph(`: ${meta.subject}`)], width: { size: 70, type: WidthType.PERCENTAGE } }),
      ],
    }),
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph("Fase / Kelas")], width: { size: 30, type: WidthType.PERCENTAGE } }),
        new TableCell({ children: [new Paragraph(`: ${meta.phase || "N/A"} / ${meta.className}`)], width: { size: 70, type: WidthType.PERCENTAGE } }),
      ],
    }),
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph("Semester / Kurikulum")], width: { size: 30, type: WidthType.PERCENTAGE } }),
        new TableCell({ children: [new Paragraph(`: ${meta.semester} / ${meta.curriculum}`)], width: { size: 70, type: WidthType.PERCENTAGE } }),
      ],
    }),
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph("Alokasi Waktu")], width: { size: 30, type: WidthType.PERCENTAGE } }),
        new TableCell({ children: [new Paragraph(`: ${meta.timeAllocation}`)], width: { size: 70, type: WidthType.PERCENTAGE } }),
      ],
    }),
  ];

  const metaTable = new Table({
    rows: metaRows,
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: "auto" },
      bottom: { style: BorderStyle.NONE, size: 0, color: "auto" },
      left: { style: BorderStyle.NONE, size: 0, color: "auto" },
      right: { style: BorderStyle.NONE, size: 0, color: "auto" },
    },
  });

  // Blueprints Table
  const tableHeader = new TableRow({
    tableHeader: true,
    children: [
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "No", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Materi/Topik", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Tujuan Pembelajaran", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Indikator Soal", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Level Kognitif", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Bentuk", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "No Soal", bold: true })] })] }),
      new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Kunci", bold: true })] })] }),
    ],
  });

  const tableBodyRows = assessment.kisiKisi.map((k) => {
    return new TableRow({
      children: [
        new TableCell({ children: [new Paragraph(String(k.no))] }),
        new TableCell({ children: [new Paragraph(k.material)] }),
        new TableCell({ children: [new Paragraph(k.tp)] }),
        new TableCell({ children: [new Paragraph(k.indicator)] }),
        new TableCell({ children: [new Paragraph(k.cognitiveLevel)] }),
        new TableCell({ children: [new Paragraph(k.questionType)] }),
        new TableCell({ children: [new Paragraph(String(k.questionNumber))] }),
        new TableCell({ children: [new Paragraph(k.answerKey)] }),
      ],
    });
  });

  const kisiTable = new Table({
    rows: [tableHeader, ...tableBodyRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  });

  const watermarkPara = new Paragraph({
    alignment: AlignmentType.RIGHT,
    children: [
      new TextRun({ text: "\n\nGenerated by Generator Soal AI - By Muh. Asriwadi AP", italics: true, size: 16, color: "888888" }),
    ],
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [titlePara, spacePara, metaTable, spacePara, kisiTable, watermarkPara],
      },
    ],
  });

  return doc;
};

/**
 * Generates DOCX for Questions (Soal)
 */
export const generateSoalDocx = async (assessment: GeneratedAssessment) => {
  const meta = assessment.metadata;

  const headerPara = new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({ text: "LEMBAR SOAL UJIAN", bold: true, size: 28 }),
      new TextRun({ text: `\n${assessment.title.toUpperCase()}`, bold: true, size: 24 }),
      new TextRun({ text: `\nTahun Pelajaran: ${meta.academicYear}`, size: 20 }),
    ],
  });

  const infoPara = new Paragraph({
    children: [
      new TextRun({ text: `Mata Pelajaran : ${meta.subject}\n`, bold: true }),
      new TextRun({ text: `Kelas / Semester : ${meta.className} (${meta.semester})\n` }),
      new TextRun({ text: `Kurikulum : ${meta.curriculum} | Alokasi Waktu : ${meta.timeAllocation}\n` }),
      new TextRun({ text: "========================================================================\n" }),
    ],
  });

  const listItems: any[] = [];

  assessment.questions.forEach((q) => {
    listItems.push(
      new Paragraph({
        children: [
          new TextRun({ text: `\n${q.no}. `, bold: true }),
          new TextRun({ text: q.question }),
        ],
      })
    );

    if (q.illustrationDescription) {
      listItems.push(
        new Paragraph({
          children: [
            new TextRun({ text: `   [Instruksi Ilustrasi/Gambar: ${q.illustrationDescription}]`, italics: true, color: "555555" }),
          ],
        })
      );
    }

    if (q.options && q.options.length > 0) {
      const optionLabels = ["A", "B", "C", "D", "E"];
      q.options.forEach((opt, idx) => {
        listItems.push(
          new Paragraph({
            children: [
              new TextRun({ text: `    ${optionLabels[idx]}. ${opt}` }),
            ],
          })
        );
      });
    } else {
      // Essay or Isian, add response space helper based on weight
      listItems.push(
        new Paragraph({
          children: [
            new TextRun({ text: `    [Bobot nilai: ${q.scoreWeight} Guna ruang jawaban secukupnya]`, italics: true, color: "888888" }),
          ],
        })
      );
    }
  });

  const divider = new Paragraph({ text: "----------------------- Akhir dari Soal Ujian -----------------------" });

  const watermarkPara = new Paragraph({
    alignment: AlignmentType.RIGHT,
    children: [
      new TextRun({ text: "\n\nGenerated by Generator Soal AI - By Muh. Asriwadi AP", italics: true, size: 16, color: "888888" }),
    ],
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [headerPara, infoPara, ...listItems, divider, watermarkPara],
      },
    ],
  });

  return doc;
};

/**
 * Generates DOCX for Answer Key (Kunci Jawaban & Bobot)
 */
export const generateKunciDocx = async (assessment: GeneratedAssessment) => {
  const meta = assessment.metadata;

  const headerPara = new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({ text: "KUNCI JAWABAN & PEMBAHASAN", bold: true, size: 28 }),
      new TextRun({ text: `\n${assessment.title.toUpperCase()}`, bold: true, size: 24 }),
    ],
  });

  const items: any[] = [];

  assessment.answers.forEach((ans) => {
    items.push(
      new Paragraph({
        children: [
          new TextRun({ text: `\nNo ${ans.no}. Kunci: `, bold: true }),
          new TextRun({ text: `${ans.correctAnswer}\n`, bold: true, color: "0055ff" }),
          new TextRun({ text: "Pembahasan: ", bold: true, italics: true }),
          new TextRun({ text: `${ans.explanation}\n` }),
          new TextRun({ text: `Skor Bobot: ${ans.score}`, color: "555555" }),
        ],
      })
    );
  });

  const guideTitle = new Paragraph({
    children: [
      new TextRun({ text: "\nPEDOMAN PENSKORAN PENILAIAN", bold: true, size: 20 }),
    ],
  });

  const guideItems = assessment.scoringGuideline.map((g) => {
    return new Paragraph({
      children: [
        new TextRun({ text: `- Tipe Soal: ${g.questionType}\n`, bold: true }),
        new TextRun({ text: `  Bobot per butir: ${g.weightPerQuestion} | Cara penskoran: ${g.description}` }),
      ],
    });
  });

  const watermarkPara = new Paragraph({
    alignment: AlignmentType.RIGHT,
    children: [
      new TextRun({ text: "\n\nGenerated by Generator Soal AI - By Muh. Asriwadi AP", italics: true, size: 16, color: "888888" }),
    ],
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [headerPara, ...items, guideTitle, ...guideItems, watermarkPara],
      },
    ],
  });

  return doc;
};

/**
 * Trigger immediate browser download for DOCX files
 */
export const downloadDocxFile = async (doc: Document, filename: string) => {
  const blob = await Packer.toBlob(doc);
  downloadBlob(blob, filename);
};

/**
 * Generates client jsPDF for offline printing
 */
export const downloadPdfFile = (type: "kisi" | "soal" | "kunci", assessment: GeneratedAssessment) => {
  const doc = new jsPDF();
  const meta = assessment.metadata;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);

  if (type === "kisi") {
    doc.text("KISI-KISI SOAL UJIAN", 105, 15, { align: "center" });
    doc.setFontSize(12);
    doc.text(assessment.title, 105, 23, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Mata Pelajaran: ${meta.subject}`, 20, 35);
    doc.text(`Fase/Kelas: ${meta.phase || "Disesuaikan"} / ${meta.className}`, 20, 42);
    doc.text(`Semester/Kurikulum: ${meta.semester} / ${meta.curriculum}`, 20, 49);

    let y = 60;
    doc.setFont("helvetica", "bold");
    doc.text("Matriks Kisi-kisi Soal:", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    assessment.kisiKisi.forEach((k) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(`No ${k.no}. ${k.material} (TP: ${k.tp.substring(0, 40)}...)`, 20, y);
      y += 6;
      doc.text(`   Indikator: ${k.indicator.substring(0, 100)}... Kunci: ${k.answerKey}`, 20, y);
      y += 8;
    });
  } else if (type === "soal") {
    doc.text("LEMBAR SOAL UJIAN", 105, 15, { align: "center" });
    doc.setFontSize(12);
    doc.text(assessment.title, 105, 23, { align: "center" });

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Mapel: ${meta.subject} | Kelas: ${meta.className} | Waktu: ${meta.timeAllocation}`, 20, 35);
    doc.text(`Tahun Pelajaran: ${meta.academicYear} | Kurikulum:${meta.curriculum}`, 20, 42);

    let y = 55;
    assessment.questions.forEach((q) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      doc.setFont("helvetica", "bold");
      doc.text(`${q.no}. ${q.question.substring(0, 95)}`, 20, y);
      y += 6;
      if (q.question.length > 95) {
        doc.text(q.question.substring(95, 190), 20, y);
        y += 6;
      }

      if (q.options && q.options.length > 0) {
        doc.setFont("helvetica", "normal");
        const labels = ["A", "B", "C", "D", "E"];
        q.options.forEach((opt, oIdx) => {
          doc.text(`  ${labels[oIdx]}. ${opt}`, 25, y);
          y += 6;
        });
      } else {
        doc.setFont("helvetica", "italic");
        doc.text("  [Jawaban Uraian - Bobot: " + q.scoreWeight + "]", 25, y);
        y += 6;
      }
      y += 4;
    });
  } else {
    doc.text("KUNCI JAWABAN & PEMBAHASAN", 105, 15, { align: "center" });
    doc.setFontSize(11);
    doc.text(assessment.title, 105, 23, { align: "center" });

    let y = 35;
    assessment.answers.forEach((ans) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      doc.setFont("helvetica", "bold");
      doc.text(`No ${ans.no}. Kunci: ${ans.correctAnswer} (Skor: ${ans.score})`, 20, y);
      y += 6;
      doc.setFont("helvetica", "normal");
      doc.text(`Pembahasan: ${ans.explanation.substring(0, 95)}`, 20, y);
      y += 6;
      if (ans.explanation.length > 95) {
        doc.text(ans.explanation.substring(95, 190), 20, y);
        y += 6;
      }
      y += 4;
    });
  }

  // Add signature Watermark clearly at bottom
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by Generator Soal AI - By Muh. Asriwadi AP", 105, 285, { align: "center" });

  doc.save(`${type}_${assessment.title.toLowerCase().replace(/\s+/g, "_")}.pdf`);
};

/**
 * Downloads all assessment documents bundled together inside a ZIP file
 */
export const downloadAllAsZip = async (assessment: GeneratedAssessment) => {
  const zip = new JSZip();

  // 1. Generate Kisi-Kisi
  const kisiDoc = await generateKisiKisiDocx(assessment);
  const kisiBlob = await Packer.toBlob(kisiDoc);
  zip.file("1_Kisi_Kisi_Soal.docx", kisiBlob);

  // 2. Generate Lembar Soal
  const soalDoc = await generateSoalDocx(assessment);
  const soalBlob = await Packer.toBlob(soalDoc);
  zip.file("2_Lembar_Soal_Ujian.docx", soalBlob);

  // 3. Generate Kunci & Pedoman
  const kunciDoc = await generateKunciDocx(assessment);
  const kunciBlob = await Packer.toBlob(kunciDoc);
  zip.file("3_Kunci_Jawaban_dan_Pembahasan.docx", kunciBlob);

  // Generate complete package
  const zipBlob = await zip.generateAsync({ type: "blob" });
  downloadBlob(zipBlob, `Asesmen_Lengkap_${assessment.title.replace(/\s+/g, "_")}.zip`);
};
